/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApproveEcosystemGameRequest {
    /// The id of the game being approved.
    #[serde(rename = "gameId")]
    pub game_id: String,
}

impl ApproveEcosystemGameRequest {
    pub fn new(game_id: String) -> ApproveEcosystemGameRequest {
        ApproveEcosystemGameRequest {
            game_id,
        }
    }
}


