/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthProfile200Response {
    /// This field has not had a description added.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "ecosystemId", skip_serializing_if = "Option::is_none")]
    pub ecosystem_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "walletId", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "connectedWalletId", skip_serializing_if = "Option::is_none")]
    pub connected_wallet_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "accessToken", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "walletDecryptKey", skip_serializing_if = "Option::is_none")]
    pub wallet_decrypt_key: Option<String>,
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Box<crate::models::WalletModel>>,
    #[serde(rename = "custodialWallet", skip_serializing_if = "Option::is_none")]
    pub custodial_wallet: Option<Box<crate::models::WalletModel>>,
}

impl AuthProfile200Response {
    pub fn new() -> AuthProfile200Response {
        AuthProfile200Response {
            id: None,
            ecosystem_id: None,
            wallet_id: None,
            connected_wallet_id: None,
            username: None,
            access_token: None,
            updated_at: None,
            created_at: None,
            wallet_decrypt_key: None,
            wallet: None,
            custodial_wallet: None,
        }
    }
}


