/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */

/// CollectionItemAttributesInnerValue : This field has not had a description added.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CollectionItemAttributesInnerValue {
}

impl CollectionItemAttributesInnerValue {
    /// This field has not had a description added.
    pub fn new() -> CollectionItemAttributesInnerValue {
        CollectionItemAttributesInnerValue {
        }
    }
}


