/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CollectionItemAttributesInner {
    /// This field has not had a description added.
    #[serde(rename = "trait_type", skip_serializing_if = "Option::is_none")]
    pub trait_type: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Box<crate::models::CollectionItemAttributesInnerValue>>,
}

impl CollectionItemAttributesInner {
    pub fn new() -> CollectionItemAttributesInner {
        CollectionItemAttributesInner {
            trait_type: None,
            value: None,
        }
    }
}


