/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCollectionItemRequestAttributesInnerValue {
}

impl CreateCollectionItemRequestAttributesInnerValue {
    pub fn new() -> CreateCollectionItemRequestAttributesInnerValue {
        CreateCollectionItemRequestAttributesInnerValue {
        }
    }
}


