/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateExchangeRequest {
    /// The blockchain you want to deploy this exchange on. Support for new blockchains are added over time.
    #[serde(rename = "chain")]
    pub chain: Chain,
}

impl CreateExchangeRequest {
    pub fn new(chain: Chain) -> CreateExchangeRequest {
        CreateExchangeRequest {
            chain,
        }
    }
}

/// The blockchain you want to deploy this exchange on. Support for new blockchains are added over time.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Chain {
    #[serde(rename = "ETHEREUM")]
    Ethereum,
    #[serde(rename = "GOERLI")]
    Goerli,
    #[serde(rename = "MATIC")]
    Matic,
    #[serde(rename = "MUMBAI")]
    Mumbai,
}

impl Default for Chain {
    fn default() -> Chain {
        Self::Ethereum
    }
}

