/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateProfileRequest {
    /// The profile's username, used to authenticate the profile. Profile usernames are globally unique across MetaFab. There cannot be 2 profiles with the same username created.
    #[serde(rename = "username")]
    pub username: String,
    /// The password to authenticate as the profile. Additionally, this password is used to encrypt/decrypt a profile's primary wallet and must be provided anytime this profile makes blockchain interactions through various endpoints.
    #[serde(rename = "password")]
    pub password: String,
}

impl CreateProfileRequest {
    pub fn new(username: String, password: String) -> CreateProfileRequest {
        CreateProfileRequest {
            username,
            password,
        }
    }
}


