/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCollectionItemRequestAttributesInner {
    #[serde(rename = "trait_type")]
    pub trait_type: String,
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
}

impl CreateCollectionItemRequestAttributesInner {
    pub fn new(trait_type: String, value: Option<serde_json::Value>) -> CreateCollectionItemRequestAttributesInner {
        CreateCollectionItemRequestAttributesInner {
            trait_type,
            value,
        }
    }
}


