/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePlayerRequest {
    /// The players username, used to authenticate the player and if desired represent them in game. Usernames are unique. There cannot be 2 users with the same username created for a game.
    #[serde(rename = "username")]
    pub username: String,
    /// The password to authenticate as the player. Additionally, this password is used to encrypt/decrypt a player's primary wallet and must be provided anytime this player makes blockchain interactions through various endpoints.
    #[serde(rename = "password")]
    pub password: String,
}

impl CreatePlayerRequest {
    pub fn new(username: String, password: String) -> CreatePlayerRequest {
        CreatePlayerRequest {
            username,
            password,
        }
    }
}


