/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCurrency200ResponseAllOfContractAllOf {
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Vec<crate::models::TransactionModel>>,
}

impl CreateCurrency200ResponseAllOfContractAllOf {
    pub fn new() -> CreateCurrency200ResponseAllOfContractAllOf {
        CreateCurrency200ResponseAllOfContractAllOf {
            transactions: None,
        }
    }
}


