/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateProfilePlayerRequest {
    /// The username to assign to the created player.
    #[serde(rename = "username")]
    pub username: String,
    /// A properly formatted permissions object that validates against the MetaFab profile permissions schema.
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<::std::collections::HashMap<String, crate::models::ProfilePermissionsValue>>,
}

impl CreateProfilePlayerRequest {
    pub fn new(username: String) -> CreateProfilePlayerRequest {
        CreateProfilePlayerRequest {
            username,
            permissions: None,
        }
    }
}


