/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GameModel {
    /// This field has not had a description added.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "walletId", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "fundingWalletId", skip_serializing_if = "Option::is_none")]
    pub funding_wallet_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "rpcs", skip_serializing_if = "Option::is_none")]
    pub rpcs: Option<serde_json::Value>,
    /// This field has not had a description added.
    #[serde(rename = "publishedKey", skip_serializing_if = "Option::is_none")]
    pub published_key: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "secretKey", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl GameModel {
    pub fn new() -> GameModel {
        GameModel {
            id: None,
            wallet_id: None,
            funding_wallet_id: None,
            email: None,
            name: None,
            rpcs: None,
            published_key: None,
            secret_key: None,
            updated_at: None,
            created_at: None,
        }
    }
}


