/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPlayerData200Response {
    #[serde(rename = "protectedData", skip_serializing_if = "Option::is_none")]
    pub protected_data: Option<serde_json::Value>,
    #[serde(rename = "publicData", skip_serializing_if = "Option::is_none")]
    pub public_data: Option<serde_json::Value>,
}

impl GetPlayerData200Response {
    pub fn new() -> GetPlayerData200Response {
        GetPlayerData200Response {
            protected_data: None,
            public_data: None,
        }
    }
}


