/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PublicPlayer {
    /// This field has not had a description added.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "gameId", skip_serializing_if = "Option::is_none")]
    pub game_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "walletId", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "connectedWalletId", skip_serializing_if = "Option::is_none")]
    pub connected_wallet_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "profileId", skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "custodialWallet", skip_serializing_if = "Option::is_none")]
    pub custodial_wallet: Option<Box<crate::models::PublicPlayerCustodialWallet>>,
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Box<crate::models::PublicPlayerCustodialWallet>>,
}

impl PublicPlayer {
    pub fn new() -> PublicPlayer {
        PublicPlayer {
            id: None,
            game_id: None,
            wallet_id: None,
            connected_wallet_id: None,
            profile_id: None,
            username: None,
            updated_at: None,
            created_at: None,
            custodial_wallet: None,
            wallet: None,
        }
    }
}


