/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCollectionItemTimelockRequest {
    /// A unix timestamp (in seconds) defining when the set timelock expires.
    #[serde(rename = "timelock")]
    pub timelock: i32,
}

impl SetCollectionItemTimelockRequest {
    pub fn new(timelock: i32) -> SetCollectionItemTimelockRequest {
        SetCollectionItemTimelockRequest {
            timelock,
        }
    }
}


