/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPlayerDataRequest {
    /// protectedData can only be set if `X-Authorization` includes credentials for the game the target player is a part of. Expects an arbitrary object allowed to contain any set of properties and nested data within those properties, including arrays.  protectedData is great for storing sensitive player data like tracking experience points, off-chain inventories, save states, and more - things that players shouldn't have the ability to directly change themselves.
    #[serde(rename = "protectedData", skip_serializing_if = "Option::is_none")]
    pub protected_data: Option<serde_json::Value>,
    /// publicData can be set if `X-Authorization` includes credentials for the target player or game the player is a part of. Expects an arbitrary object allowed to contain any set of properties and nested data within those properties, including arrays.  publicData is great for storing player preferences like in-game settings, non-sensitive data and more. Anything that a player should have the ability to directly change themselves without client or server verification can be stored in publicData.
    #[serde(rename = "publicData", skip_serializing_if = "Option::is_none")]
    pub public_data: Option<serde_json::Value>,
}

impl SetPlayerDataRequest {
    pub fn new() -> SetPlayerDataRequest {
        SetPlayerDataRequest {
            protected_data: None,
            public_data: None,
        }
    }
}


