/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetPlayerDataRequest {
    /// protectedData can only be set if `X-Authorization` includes credentials for the game the target player is a part of. Expects an arbitrary object allowed to contain any set of properties and nested data within those properties, including arrays.
    #[serde(rename = "protectedData", skip_serializing_if = "Option::is_none")]
    pub protected_data: Option<serde_json::Value>,
    /// publicData can be set if `X-Authorization` includes credentials for the target player or game the player is a part of. Expects an arbitrary object allowed to contain any set of properties and nested data within those properties, including arrays.
    #[serde(rename = "publicData", skip_serializing_if = "Option::is_none")]
    pub public_data: Option<serde_json::Value>,
}

impl SetPlayerDataRequest {
    pub fn new() -> SetPlayerDataRequest {
        SetPlayerDataRequest {
            protected_data: None,
            public_data: None,
        }
    }
}


