/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetCollectionApprovalRequest {
    /// A true or false value approves or disapproves the provided address or address associated with the provided walletId.
    #[serde(rename = "approved")]
    pub approved: bool,
    /// A valid EVM based address to allow control over the authenticating game or player's wallet items for this collection.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// A wallet id within the MetaFab ecosystem to allow control over the authenticating game or player's wallet items for this collection.
    #[serde(rename = "walletId", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<Vec<String>>,
}

impl SetCollectionApprovalRequest {
    pub fn new(approved: bool) -> SetCollectionApprovalRequest {
        SetCollectionApprovalRequest {
            approved,
            address: None,
            wallet_id: None,
        }
    }
}


