/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferContractOwnershipRequest {
    /// A wallet address to assign as the new owner and administrator of the target smart contract.
    #[serde(rename = "ownerAddress")]
    pub owner_address: String,
}

impl TransferContractOwnershipRequest {
    pub fn new(owner_address: String) -> TransferContractOwnershipRequest {
        TransferContractOwnershipRequest {
            owner_address,
        }
    }
}


