/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferCurrencyRequest {
    /// A valid EVM based address to transfer currency to. For example, `0x39cb70F972E0EE920088AeF97Dbe5c6251a9c25D`.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Any wallet id within the MetaFab ecosystem to transfer currency to.
    #[serde(rename = "walletId", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    /// The amount of currency to transfer.
    #[serde(rename = "amount")]
    pub amount: f32,
    /// An optional uint256 number to reference the transfer. Commonly used to identify transfers intended to pay for game items or services.
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<f32>,
}

impl TransferCurrencyRequest {
    pub fn new(amount: f32) -> TransferCurrencyRequest {
        TransferCurrencyRequest {
            address: None,
            wallet_id: None,
            amount,
            reference: None,
        }
    }
}


