/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateProfilePlayerRequest {
    /// A properly formatted permissions object that validates against the MetaFab profile permissions schema.
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<::std::collections::HashMap<String, crate::models::ProfilePermissionsValue>>,
}

impl UpdateProfilePlayerRequest {
    pub fn new() -> UpdateProfilePlayerRequest {
        UpdateProfilePlayerRequest {
            permissions: None,
        }
    }
}


