/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateEcosystemRequest {
    /// A new name. Replaces the ecosystem's current name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A new email address. The ecosystem's old email will no longer be valid for account authentication. `currentPassword` must also be provided.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The ecosystem's current password. Must be provided if setting `newPassword` or `email`.
    #[serde(rename = "currentPassword", skip_serializing_if = "Option::is_none")]
    pub current_password: Option<String>,
    /// A new password. The ecosystem's old password will no longer be valid.
    #[serde(rename = "newPassword", skip_serializing_if = "Option::is_none")]
    pub new_password: Option<String>,
    /// A base64 string of the icon image for this ecosystem. Supported image formats are `jpg`, `jpeg`, `png`, `gif` Recommended size is 512x512 pixels, or 1:1 aspect ratio. This image is used for your profile authorization flow and other MetaFab features for your ecosystem.
    #[serde(rename = "iconImageBase64", skip_serializing_if = "Option::is_none")]
    pub icon_image_base64: Option<String>,
    /// A base64 string of the cover image for this ecosystem. Supported image formats are `jpg`, `jpeg`, `png`, `gif`. Recommended size is 1600x1000 pixels, or 16:10 aspect ratio.  This image is used as the background image for your profile authorization flow and other MetaFab features for your ecosystem.
    #[serde(rename = "coverImageBase64", skip_serializing_if = "Option::is_none")]
    pub cover_image_base64: Option<String>,
    /// A valid hex color code. This color is used for your profile authorization flow to control the color of buttons and other brandable MetaFab features for your ecosystem.
    #[serde(rename = "primaryColorHex", skip_serializing_if = "Option::is_none")]
    pub primary_color_hex: Option<String>,
    /// Revokes the ecosystem's previous published key and returns a new one if true.
    #[serde(rename = "resetPublishedKey", skip_serializing_if = "Option::is_none")]
    pub reset_published_key: Option<bool>,
    /// Revokes the ecosystem's previous secret key and returns a new on if true.
    #[serde(rename = "resetSecretKey", skip_serializing_if = "Option::is_none")]
    pub reset_secret_key: Option<bool>,
}

impl UpdateEcosystemRequest {
    pub fn new() -> UpdateEcosystemRequest {
        UpdateEcosystemRequest {
            name: None,
            email: None,
            current_password: None,
            new_password: None,
            icon_image_base64: None,
            cover_image_base64: None,
            primary_color_hex: None,
            reset_published_key: None,
            reset_secret_key: None,
        }
    }
}


