/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateProfilePlayer200ResponseAllOf {
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Box<crate::models::WalletModel>>,
    #[serde(rename = "custodialWallet", skip_serializing_if = "Option::is_none")]
    pub custodial_wallet: Option<Box<crate::models::WalletModel>>,
}

impl UpdateProfilePlayer200ResponseAllOf {
    pub fn new() -> UpdateProfilePlayer200ResponseAllOf {
        UpdateProfilePlayer200ResponseAllOf {
            wallet: None,
            custodial_wallet: None,
        }
    }
}


