/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdatePlayer200Response {
    /// This field has not had a description added.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "gameId", skip_serializing_if = "Option::is_none")]
    pub game_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "walletId", skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "connectedWalletId", skip_serializing_if = "Option::is_none")]
    pub connected_wallet_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "profileId", skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "accessToken", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "profilePermissions", skip_serializing_if = "Option::is_none")]
    pub profile_permissions: Option<serde_json::Value>,
    /// This field has not had a description added.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// This field has not had a description added.
    #[serde(rename = "walletDecryptKey", skip_serializing_if = "Option::is_none")]
    pub wallet_decrypt_key: Option<String>,
}

impl UpdatePlayer200Response {
    pub fn new() -> UpdatePlayer200Response {
        UpdatePlayer200Response {
            id: None,
            game_id: None,
            wallet_id: None,
            connected_wallet_id: None,
            profile_id: None,
            username: None,
            access_token: None,
            profile_permissions: None,
            updated_at: None,
            created_at: None,
            wallet_decrypt_key: None,
        }
    }
}


